sonar.projectKey=Solierrr_google-registry
sonar.organization=solierrr

# Código de produção x código de teste.
sonar.sources=app
sonar.tests=tests

# Relatório de cobertura gerado pelo pytest-cov
sonar.python.coverage.reportPaths=coverage.xml

# Encoding do código-fonte
sonar.sourceEncoding=UTF-8

# Arquivos irrelevantes para a análise
sonar.exclusions=**/__pycache__/**,docs/**
